# This is a basic workflow to help you get started with Actions

name: SyncAppConfiguration

on:
  push:
    branches:
      - 'main'
    paths:
      - 'configuration/**'
      
  workflow_dispatch:

jobs:
  syncconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Import to app Configuration
        uses: azure/appconfiguration-sync@v1
        with:
          configurationFile: 'appsettings.json'
          format: 'json'
          # Replace <ConnectionString> with the name of the secret in your repository
          connectionString: "Endpoint=https://appc-rapidx.azconfig.io;Id=5Tcc-lh-s0:G5Gyd6/XARn3jPw5RQqV;Secret=4n9zA74KFQQBSYYrvThUltnMHDRBB3McdihsJVwxGiI="
          separator: '.'
          strict: true
      - name: Export to app service
        run: az appconfig kv export --name appc-rapidx --destination app-demo-dotnet --appservice-account /subscriptions/ce15a333-79ee-4b82-9bdb-147ea6324d30/resourceGroups/rg-elixir-demo/providers/Microsoft.Web/sites/app-demo-dotnet --label prod
